In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import sys

sys.path.append("..")

In [3]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier as DecisionTreeClassifier_sk
from sklearn.tree import export_text as export_text_sk
from sklearn.tree import plot_tree as plot_tree_sk

In [4]:
iris = load_iris()
X, y = load_iris(return_X_y=True)

In [5]:
np.unique(y)

array([0, 1, 2])

In [6]:
X.shape, y.shape

((150, 4), (150,))

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
from algosfromscratch.supervised_learning import DecisionTreeClassifier

In [9]:
clf = DecisionTreeClassifier(criterion='gini', max_depth=None, min_samples_split=2, min_impurity_decrease=0.0)

In [10]:
clf.fit(X_train, y_train)

In [11]:
from algosfromscratch.utils.tree import export_text

In [12]:
print(export_text(clf.root, feature_names=iris['feature_names']))

|---  petal length (cm) <= 2.35
|   |--- class: 0
|---  petal length (cm) > 2.35
|   |---  petal length (cm) <= 4.95
|   |   |---  petal width (cm) <= 1.65
|   |   |   |--- class: 1
|   |   |---  petal width (cm) > 1.65
|   |   |   |---  sepal width (cm) <= 3.1
|   |   |   |   |--- class: 2
|   |   |   |---  sepal width (cm) > 3.1
|   |   |   |   |--- class: 1
|   |---  petal length (cm) > 4.95
|   |   |---  petal length (cm) <= 5.05
|   |   |   |---  sepal length (cm) <= 6.5
|   |   |   |   |--- class: 2
|   |   |   |---  sepal length (cm) > 6.5
|   |   |   |   |--- class: 1
|   |   |---  petal length (cm) > 5.05
|   |   |   |--- class: 2



In [13]:
y_pred = clf.predict(X_test)

In [14]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [15]:
clf_sk = DecisionTreeClassifier_sk(criterion='gini', max_depth=None, min_samples_split=2, min_impurity_decrease=0.0)

In [16]:
clf_sk.fit(X_train, y_train)

DecisionTreeClassifier()

In [17]:
y_pred_sk = clf_sk.predict(X_test)

In [18]:
y_pred_sk

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [19]:
print(export_text_sk(clf_sk, feature_names=iris['feature_names']))

|--- petal width (cm) <= 0.75
|   |--- class: 0
|--- petal width (cm) >  0.75
|   |--- petal length (cm) <= 4.95
|   |   |--- petal width (cm) <= 1.65
|   |   |   |--- class: 1
|   |   |--- petal width (cm) >  1.65
|   |   |   |--- sepal width (cm) <= 3.10
|   |   |   |   |--- class: 2
|   |   |   |--- sepal width (cm) >  3.10
|   |   |   |   |--- class: 1
|   |--- petal length (cm) >  4.95
|   |   |--- petal length (cm) <= 5.05
|   |   |   |--- sepal length (cm) <= 6.50
|   |   |   |   |--- class: 2
|   |   |   |--- sepal length (cm) >  6.50
|   |   |   |   |--- class: 1
|   |   |--- petal length (cm) >  5.05
|   |   |   |--- class: 2



In [20]:
y_pred == y_pred_sk

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

# Titanic

In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('../data/titanic.csv')

In [23]:
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [24]:
X = df[['Pclass', 'Sex', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare']].to_numpy()

In [25]:
y = df['Survived'].to_numpy()

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [27]:
clf = DecisionTreeClassifier(criterion='gini', max_depth=None, min_samples_split=2, min_impurity_decrease=0.0)

In [28]:
clf.fit(X_train, y_train)

In [29]:
y_pred = clf.predict(X_test)

In [30]:
y_pred

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,

In [31]:
print(export_text(clf.root, feature_names=['Pclass', 'Sex', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare']))

|---  Sex == female
|   |---  Pclass <= 2.5
|   |   |---  Age <= 2.5
|   |   |   |--- class: 0
|   |   |---  Age > 2.5
|   |   |   |---  Fare <= 28.85625
|   |   |   |   |---  Age <= 37.0
|   |   |   |   |   |---  Siblings/Spouses Aboard <= 0.5
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |---  Siblings/Spouses Aboard > 0.5
|   |   |   |   |   |   |---  Fare <= 22.0
|   |   |   |   |   |   |   |---  Age <= 28.5
|   |   |   |   |   |   |   |   |---  Fare <= 17.42915
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |---  Fare > 17.42915
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |---  Age > 28.5
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |---  Fare > 22.0
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |---  Age > 37.0
|   |   |   |   |   |---  Age <= 39.0
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |---  Age > 39.0
|   |   |   |   |   |   |---  Fare <= 27.6

In [32]:
clf_sk = DecisionTreeClassifier_sk(criterion='gini', max_depth=None, min_samples_split=2, min_impurity_decrease=0.0)

In [33]:
# Need to one-hot encode Sex for scikit-learn
X_train_sk, X_test_sk = X_train.copy(), X_test.copy()
X_train_sk[:,1] = [0 if s == 'female' else 1 for s in X_train_sk[:,1]]
X_test_sk[:,1] = [0 if s == 'female' else 1 for s in X_test_sk[:,1]]

In [34]:
clf_sk.fit(X_train_sk, y_train)

DecisionTreeClassifier()

In [35]:
y_pred_sk = clf_sk.predict(X_test_sk)

In [36]:
y_pred_sk

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,

In [37]:
print(export_text_sk(clf_sk, feature_names=['Pclass', 'Sex', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare']))

|--- Sex <= 0.50
|   |--- Pclass <= 2.50
|   |   |--- Age <= 2.50
|   |   |   |--- class: 0
|   |   |--- Age >  2.50
|   |   |   |--- Fare <= 28.86
|   |   |   |   |--- Age <= 37.00
|   |   |   |   |   |--- Siblings/Spouses Aboard <= 0.50
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- Siblings/Spouses Aboard >  0.50
|   |   |   |   |   |   |--- Fare <= 22.00
|   |   |   |   |   |   |   |--- Fare <= 17.43
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- Fare >  17.43
|   |   |   |   |   |   |   |   |--- Siblings/Spouses Aboard <= 2.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- Siblings/Spouses Aboard >  2.00
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- Fare >  22.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- Age >  37.00
|   |   |   |   |   |--- Fare <= 27.63
|   |   |   |   |   |   |--- Fare <= 14.38
|   |   |   |   |   |   |   |--- Fare <= 11.

In [38]:
y_pred == y_pred_sk

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score(y_pred, y_test)

0.7612612612612613

In [41]:
accuracy_score(y_pred_sk, y_test)

0.7545045045045045