In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import sys

sys.path.append("..")

In [3]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB as sk_GaussianNB
from sklearn.naive_bayes import MultinomialNB as sk_MultinomialNB

# Gaussian

In [4]:
X, y = load_iris(return_X_y=True)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [6]:
from algosfromscratch.supervised_learning import GaussianNB

In [7]:
gnb = GaussianNB()

In [8]:
gnb.fit(X_train, y_train)

In [9]:
y_pred = gnb.predict(X_test)

In [10]:
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 75 points : 4


In [11]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 0, 2, 1, 1, 1,
       1, 2, 0, 0, 2, 1, 0, 0, 1])

In [12]:
gnb_sk = sk_GaussianNB()

In [13]:
gnb_sk.fit(X_train, y_train)

GaussianNB()

In [14]:
y_pred_sk = gnb_sk.predict(X_test)

In [15]:
y_pred == y_pred_sk

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

# Multinomial

In [16]:
X = np.random.randint(5, size=(100, 100))

In [17]:
y = np.random.randint(3, size=(100,))

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [19]:
from algosfromscratch.supervised_learning import MultinomialNB

In [20]:
mnb = MultinomialNB()

In [21]:
mnb.fit(X_train, y_train)

In [22]:
y_pred = mnb.predict(X_test)

In [23]:
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 50 points : 33


In [24]:
y_pred

array([0, 2, 1, 2, 2, 0, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 0,
       2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 1,
       0, 1, 1, 0, 0, 2])

In [25]:
mnb_sk = sk_MultinomialNB()

In [26]:
mnb_sk.fit(X_train, y_train)

MultinomialNB()

In [27]:
y_pred_sk = mnb_sk.predict(X_test)

In [28]:
y_pred_sk

array([0, 2, 1, 2, 2, 0, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 0,
       2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 1,
       0, 1, 1, 0, 0, 2])

In [29]:
y_pred == y_pred_sk

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])