In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import sys

sys.path.append("..")

In [3]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier as RandomForestClassifier_sk

In [4]:
iris = load_iris()
X, y = load_iris(return_X_y=True)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [6]:
from algosfromscratch.supervised_learning import RandomForestClassifier

In [7]:
clf = RandomForestClassifier(n_estimators=100, criterion='entropy', max_depth=None, min_samples_split=2,
                             max_features='auto', min_impurity_decrease=0.0, bootstrap=True,
                             random_state=647, max_samples=0.50)

In [8]:
clf.fit(X_train, y_train)

In [9]:
y_pred = clf.predict(X_test)

In [10]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [11]:
clf_sk = RandomForestClassifier_sk(n_estimators=100, criterion='entropy', max_depth=None, min_samples_split=2,
                                   max_features='auto', min_impurity_decrease=0.0, bootstrap=True,
                                   random_state=647, max_samples=0.50)

In [12]:
clf_sk.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_samples=0.5, random_state=647)

In [13]:
y_pred_sk = clf_sk.predict(X_test)

In [14]:
y_pred_sk

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [15]:
y_pred == y_pred_sk

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

# Titanic

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('../data/titanic.csv')

In [18]:
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [19]:
X = df[['Pclass', 'Sex', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare']].to_numpy()

# Make female 1 and male 0
X[:,1] = [0 if s == 'female' else 1 for s in X[:,1]]

In [20]:
y = df['Survived'].to_numpy()

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [22]:
clf = RandomForestClassifier(n_estimators=1000, criterion='gini', max_depth=None, min_samples_split=2,
                             max_features='log2', min_impurity_decrease=0.0, bootstrap=True,
                             random_state=647, max_samples=0.50)

In [ ]:
clf.fit(X_train, y_train)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
clf_sk = RandomForestClassifier_sk(n_estimators=1000, criterion='gini', max_depth=None, min_samples_split=2,
                                   max_features='log2', min_impurity_decrease=0.0, bootstrap=True,
                                   random_state=647, max_samples=0.50)

In [ ]:
clf_sk.fit(X_train, y_train)

In [ ]:
y_pred_sk = clf_sk.predict(X_test)

In [ ]:
y_pred == y_pred_sk

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_pred, y_test)

In [ ]:
accuracy_score(y_pred_sk, y_test)